name: CI/CD Backend

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest  # Utilise un runner Ubuntu

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Copy deployment files
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          source: "Dockerfile,docker-compose.yml,pom.xml,mvnw,.mvn,src"
          target: "/root/andos_eextraits_back"

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            TARGET_DIR="/root/andos_eextraits_back"
            
            if [ ! -d "$TARGET_DIR" ]; then
            echo "Error: Directory $TARGET_DIR does not exist."
            exit 1
            fi
            cd $TARGET_DIR
            
            echo "Creating .env file in $TARGET_DIR"
            echo "MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}" > .env
            echo "MYSQL_DATABASE=${{ secrets.MYSQL_DATABASE }}" >> .env
            echo "MYSQL_USER=${{ secrets.MYSQL_USER }}" >> .env
            echo "MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}" >> .env
            
            docker-compose build andos-eextraits-back
            docker-compose -f docker-compose.yml up -d --force-recreate andos-eextraits-back
            docker image prune -f
            
            rm -rf Dockerfile docker-compose.yml pom.xml mvnw .mvn src