name: CI/CD Frontend

on:
  push:
    branches:
      - deploy/andos-eextraits.0.0.1  # Déclenche le workflow à chaque push sur la branche 'main'

env:
  VITE_BASE_URL: ${{ secrets.VITE_BASE_URL }} # Accède à la variable d'environnement sécurisée

jobs:
  deploy:
    runs-on: ubuntu-latest  # Utilise un runner Ubuntu

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile  # Assurez-vous que ce chemin est correct
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/andos-eextraits-back:latest

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /andos-eextraits-back
            echo "VITE_BASE_URL=${{ secrets.VITE_BASE_URL }}" > .env.production
            docker-compose pull
            docker-compose up -d --force-recreate